---
- name: Install Pipewire
  community.general.pacman:
    name:
      - pipewire
      - pipewire-alsa
      - pipewire-jack
      - pipewire-media-session
      - pipewire-pulse
      - gst-plugin-pipewire
      - libpulse
    state: present