---
- name: Install Neovim
  community.general.pacman:
    name: neovim
    state: present

- name: Install Neovim Symlink
  community.general.pacman:
    name: neovim-symlinks
    state: present

- name: Install Neovim Python Client
  community.general.pacman:
    name: python-pynvim
    state: present
